
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.0.17.0
//      You can make changes to this file and they will not be overwritten when saving.
//  </auto-generated>
// -----------------------------------------------------------------------------

using System.Text;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using RabbitMQ.Client;

namespace Stegosaurus.Dispatcher.Main{
    using Terminal.Gui;
    
    
    public partial class MyView {
        
        public MyView() {
            InitializeComponent();
            btn_connect.Clicked += Btn_connectOnClicked;
        }

        private async void Btn_connectOnClicked()
        {
            string msg;
            var factory = new ConnectionFactory
            {
                HostName = "localhost",
            }; 
            
            dbg_log.AppendText("[INFO] Connecting to RabbitMQ...\n");
            await using var connection = await factory.CreateConnectionAsync();
            await using var channel = await connection.CreateChannelAsync();

            await channel.ExchangeDeclareAsync("dispatch", ExchangeType.Topic);
            dbg_log.AppendText("[INFO] Declaring exchange to RabbitMQ...\n");

            //await channel.QueueDeclareAsync(queue: "Creation", durable: false, exclusive: false, autoDelete: false, arguments: null);
            // read JSON directly from a file
            using (var file = File.OpenText(@"C:\Users\thega\AppData\Roaming\StegoShard\request.json"))
            using (var reader = new JsonTextReader(file))
            {
                var o2 = (JObject)JToken.ReadFrom(reader);
                msg = o2.ToString();
            }

            var body = Encoding.UTF8.GetBytes(msg);

            await channel.BasicPublishAsync("dispatch", txt_id.Text + ".creation", body);
            dbg_log.AppendText("[INFO] Sending message to RabbitMQ...\n");
        }
    }
}
